version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    links:
      - postgres
      - redis
      - selenium
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=app
      - TEST_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - "4444:4444"
      - "5900:5900"
    logging:
      driver: none
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres: